"""Figure 5 -- Fatigue crack growth and crack formation generated by the
shared barrier architecture.
  A. Four representative systems from the six-system atlas (QUALIFIED).
  B. Long-growth hierarchy persistence + orientation-dependent growth rate
     (QUALIFIED for growth-rate numbers; geometric path deflection is
     explicitly NOT verified -- SOURCE_RESULT_LOCATED_AND_STRUCTURALLY_MATCHED
     overall for Fig5B).
  C. Censor-aware connected-crack S-N response, blunt-notch problem
     (QUALIFIED).
  D. Representative shielded/unshielded spatial fields (SOURCE_RESULT_LOCATED_
     AND_STRUCTURALLY_MATCHED -- qualitative only, no cross-image ratio).

Descriptive display labels are used throughout; internal case IDs are
preserved only in the source-data CSV / manifest (see style_common.SYSTEM_LABEL).

Source: codex/v10.2.30-paper-evidence-independent-verifier @
cbf2cf8bf73c649c1b87acd6a6a94f322f936bcc, source_bundle_figures_2_4/
  fig5A_atlas_2d_paris_points.csv
  fig5B_multiseed_r_curve_mean_curves.csv
  fig5B_orientation_theta{30,45}_atlas_2d_paris_points.csv
  fig5C_compact_sn_reconstruction.json
  fig5D_fields_{shielded,no_shield}_seed5_900MPa.png
"""
from __future__ import annotations

import csv
import json
import shutil
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style_common import (SYSTEM_COLOR, SYSTEM_LABEL, SYSTEM_ORDER, MAIN_TEXT_FOUR_SYSTEMS,
                           FIGSIZE_SINGLE_COL, FIGSIZE_DOUBLE_COL_TALL, add_panel_label, savefig_all,
                           sha256_of, style_log_axis)

PKG = Path(__file__).resolve().parents[1]
BUNDLE = Path("/Volumes/Data/Data/Nanopillar_calculation/PF-fracture-fatigue_worktrees/"
              "v10230-final-manuscript-figure-package/artifacts/paper_simulation_completion/"
              "source_bundle_figures_2_4")
SRC_OUT = PKG / "04_SOURCE_DATA" / "MAIN_TEXT"
PANELS_OUT = PKG / "01_MAIN_TEXT" / "INDIVIDUAL_PANELS"
COMPOSITE_OUT = PKG / "01_MAIN_TEXT" / "COMPOSITE_FIGURES"
PDF_OUT = PKG / "01_MAIN_TEXT" / "PDF"
SVG_OUT = PKG / "01_MAIN_TEXT" / "SVG"
PNG_OUT = PKG / "01_MAIN_TEXT" / "PNG_600DPI"


def _read_csv(name):
    with (BUNDLE / name).open() as fh:
        return list(csv.DictReader(fh))


def panel_A(ax, rows, systems=MAIN_TEXT_FOUR_SYSTEMS):
    for case in systems:
        rs = sorted([r for r in rows if r["case_label"] == case], key=lambda r: float(r["DeltaK_MPa_sqrtm"]))
        dk = [float(r["DeltaK_MPa_sqrtm"]) for r in rs]
        rate = [float(r["plot_da_dN_m_per_cycle"]) for r in rs]
        censored = [r["is_censored_upper_bound"] == "True" for r in rs]
        dk_ok = [d for d, c in zip(dk, censored) if not c]
        rate_ok = [r for r, c in zip(rate, censored) if not c]
        dk_c = [d for d, c in zip(dk, censored) if c]
        rate_c = [r for r, c in zip(rate, censored) if c]
        ax.plot(dk_ok, rate_ok, color=SYSTEM_COLOR[case], marker="o", markersize=4,
                linewidth=1.2, label=SYSTEM_LABEL[case])
        if dk_c:
            ax.plot(dk_c, rate_c, color=SYSTEM_COLOR[case], marker="v", markersize=5,
                    linestyle="none", markerfacecolor="none")
    style_log_axis(ax, "both")
    ax.set_xlabel(r"$\Delta K$ (MPa$\sqrt{\mathrm{m}}$)")
    ax.set_ylabel(r"$da/dN$ (m/cycle)")
    ax.set_title("Four representative systems\n(triangle = upper-bound censor)", fontsize=8.5)


def panel_B(ax, mean_curves, orient30, orient45):
    cases = sorted(set(r["case_label"] for r in mean_curves))
    for case in SYSTEM_ORDER:
        rs = sorted([r for r in mean_curves if r["case_label"] == case], key=lambda r: float(r["extension_um"]))
        x = [float(r["extension_um"]) for r in rs]
        y = [float(r["KJ_mean_MPa_sqrtm"]) for r in rs]
        ax.plot(x, y, color=SYSTEM_COLOR[case], linewidth=1.4, label=SYSTEM_LABEL[case])
    ax.set_xlabel(r"Crack extension ($\mu$m)")
    ax.set_ylabel(r"$K_J$ (MPa$\sqrt{\mathrm{m}}$)")
    ax.set_title("Long-growth hierarchy persistence\n(6-system rank order stable at extremes, all 5 checkpoints)",
                 fontsize=8)

    da30 = float(orient30[0]["da_dN_m_per_cycle"])
    da45 = float(orient45[0]["da_dN_m_per_cycle"])
    axins = ax.inset_axes([0.55, 0.12, 0.4, 0.35])
    axins.bar([0, 1], [da30, da45],
              color=[SYSTEM_COLOR["plastic_shielded_case64_M1"], "0.5"])
    axins.set_xticks([0, 1])
    axins.set_xticklabels(["30$^\\circ$", "45$^\\circ$"])
    axins.set_yscale("log")
    axins.set_ylabel("da/dN\n(m/cyc)", fontsize=6)
    axins.set_title(f"Orientation ratio $\\approx${max(da30,da45)/min(da30,da45):.0f}x\n"
                     "(growth rate only;\npath deflection not\ngeometrically verified)", fontsize=5.8)
    axins.tick_params(labelsize=6)


def panel_C(ax, sn_data):
    jobs = sn_data["jobs"]
    for cond, color, marker, dy in [("no_shield", "0.15", "o", -4), ("shielded", "tab:red", "s", 4)]:
        js = [j for j in jobs if j["condition"] == cond]
        first_connected, first_censored = True, True
        for j in js:
            y = j["sigma_a_MPa"] + dy
            cond_label = "No shield" if cond == "no_shield" else "Shielded"
            if j["cycles_root_connected"] is not None:
                lbl = f"{cond_label}: connected" if first_connected else None
                first_connected = False
                ax.scatter(j["cycles_root_connected"], y, color=color, marker=marker, s=32,
                           edgecolor="black", linewidth=0.3, label=lbl, zorder=3)
            else:
                lbl = f"{cond_label}: right-censored" if first_censored else None
                first_censored = False
                ax.scatter(3e9, y, color=color, marker=">", s=45, facecolor="none",
                           edgecolor=color, linewidth=1.4, label=lbl, zorder=3)
    ax.set_xscale("log")
    ax.set_xlim(1e6, 1e10)
    ax.set_ylim(680, 920)
    ax.set_yticks([700, 900])
    ax.set_xlabel("Cycles to root connection\n(right-pointing open marker = right-censored)")
    ax.set_ylabel(r"Nominal $\sigma_a$ (MPa)")
    ax.set_title("Censor-aware connected-crack S-N\n(blunt-notch, seeds 2-5)", fontsize=8.5)
    ax.legend(fontsize=6, loc="upper left", bbox_to_anchor=(1.0, 1.02))


def panel_D(ax_ns, ax_sh):
    img_ns = mpimg.imread(BUNDLE / "fig5D_fields_no_shield_seed5_900MPa.png")
    img_sh = mpimg.imread(BUNDLE / "fig5D_fields_shielded_seed5_900MPa.png")
    ax_ns.imshow(img_ns); ax_ns.axis("off")
    ax_ns.set_title("Unshielded (seed 5, 900 MPa)", fontsize=8)
    ax_sh.imshow(img_sh); ax_sh.axis("off")
    ax_sh.set_title("Shielded (seed 5, 900 MPa)\n(no verified common field normalization)", fontsize=8)


def composite(rows_a, mean_curves, orient30, orient45, sn_data):
    fig = plt.figure(figsize=FIGSIZE_DOUBLE_COL_TALL)
    gs = fig.add_gridspec(3, 2, height_ratios=[1.0, 1.0, 0.9])
    axA = fig.add_subplot(gs[0, 0]); panel_A(axA, rows_a); add_panel_label(axA, "A")
    axA.legend(fontsize=6, loc="lower left")
    axB = fig.add_subplot(gs[0, 1]); panel_B(axB, mean_curves, orient30, orient45); add_panel_label(axB, "B")
    axB.legend(fontsize=5.5, loc="upper left", ncol=1, bbox_to_anchor=(1.0, 1.0))
    axC = fig.add_subplot(gs[1, 0]); panel_C(axC, sn_data); add_panel_label(axC, "C")
    axD1 = fig.add_subplot(gs[1, 1]); axD1.axis("off")
    axD1.text(0.5, 0.5, "Panel D: representative spatial\nfields (see below)", ha="center", va="center",
              fontsize=8, transform=axD1.transAxes)
    axD2 = fig.add_subplot(gs[2, 0]); axD3 = fig.add_subplot(gs[2, 1])
    panel_D(axD2, axD3)
    add_panel_label(axD2, "D")
    fig.suptitle("Figure 5. Fatigue crack growth and crack formation generated by the shared barrier "
                 "architecture", fontsize=9, y=1.0)
    fig.tight_layout()
    return fig


def main():
    rows_a = _read_csv("fig5A_atlas_2d_paris_points.csv")
    mean_curves = _read_csv("fig5B_multiseed_r_curve_mean_curves.csv")
    orient30 = _read_csv("fig5B_orientation_theta30_atlas_2d_paris_points.csv")
    orient45 = _read_csv("fig5B_orientation_theta45_atlas_2d_paris_points.csv")
    sn_data = json.loads((BUNDLE / "fig5C_compact_sn_reconstruction.json").read_text())

    SRC_OUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for name in ["fig5A_atlas_2d_paris_points.csv", "fig5B_multiseed_r_curve_mean_curves.csv",
                 "fig5B_orientation_theta30_atlas_2d_paris_points.csv",
                 "fig5B_orientation_theta45_atlas_2d_paris_points.csv",
                 "fig5C_compact_sn_reconstruction.json",
                 "fig5D_fields_no_shield_seed5_900MPa.png", "fig5D_fields_shielded_seed5_900MPa.png"]:
        dest = SRC_OUT / name
        dest.write_bytes((BUNDLE / name).read_bytes())
        manifest[name] = sha256_of(dest)
    # Internal-case-ID -> descriptive-label mapping, explicitly archived per the traceability contract.
    (SRC_OUT / "fig5A_system_id_to_label_mapping.json").write_text(
        json.dumps(SYSTEM_LABEL, indent=2))

    hashes = {}
    fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE_COL); panel_A(ax, rows_a); add_panel_label(ax, "A")
    ax.legend(fontsize=7, loc="lower left"); fig.tight_layout()
    hashes["Fig5A"] = savefig_all(fig, "Fig5A", PANELS_OUT, PANELS_OUT, PANELS_OUT)
    savefig_all(fig, "Fig5A", PDF_OUT, SVG_OUT, PNG_OUT); plt.close(fig)

    fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE_COL); panel_B(ax, mean_curves, orient30, orient45)
    add_panel_label(ax, "B"); ax.legend(fontsize=6, loc="upper left", bbox_to_anchor=(1.02, 1.0))
    fig.tight_layout()
    hashes["Fig5B"] = savefig_all(fig, "Fig5B", PANELS_OUT, PANELS_OUT, PANELS_OUT)
    savefig_all(fig, "Fig5B", PDF_OUT, SVG_OUT, PNG_OUT); plt.close(fig)

    fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE_COL); panel_C(ax, sn_data); add_panel_label(ax, "C")
    fig.tight_layout()
    hashes["Fig5C"] = savefig_all(fig, "Fig5C", PANELS_OUT, PANELS_OUT, PANELS_OUT)
    savefig_all(fig, "Fig5C", PDF_OUT, SVG_OUT, PNG_OUT); plt.close(fig)

    fig, (axd1, axd2) = plt.subplots(1, 2, figsize=(10, 5))
    panel_D(axd1, axd2); add_panel_label(axd1, "D")
    fig.tight_layout()
    hashes["Fig5D"] = savefig_all(fig, "Fig5D", PANELS_OUT, PANELS_OUT, PANELS_OUT)
    savefig_all(fig, "Fig5D", PDF_OUT, SVG_OUT, PNG_OUT); plt.close(fig)

    fig_comp = composite(rows_a, mean_curves, orient30, orient45, sn_data)
    hashes["Figure5_composite"] = savefig_all(fig_comp, "Figure5_composite", COMPOSITE_OUT, COMPOSITE_OUT, COMPOSITE_OUT)
    savefig_all(fig_comp, "Figure5_composite", PDF_OUT, SVG_OUT, PNG_OUT)
    plt.close(fig_comp)

    (SRC_OUT / "fig5_source_data_hashes.json").write_text(json.dumps(
        dict(source_files=manifest, figure_hashes=hashes), indent=2, default=str))
    print("Figure 5: wrote 4 panels + 1 composite")


if __name__ == "__main__":
    main()
