"""Figure 6 -- Cross-phenomenon relationships generated by the shared
barrier landscape. QUALIFIED_SOURCE_RESULT_VERIFIED (Fig6A/B/C).

Panel A: Cramer's V is plotted as its (mathematically nonnegative)
magnitude only -- never a negative value. Association direction, where
scientifically relevant, is a caption-level statement, not a plotted sign
(see 06_CAPTIONS_AND_NOTES/figure_captions.md and
manuscript_corrections.md).

Source: codex/v10.2.30-paper-evidence-independent-verifier @
cbf2cf8bf73c649c1b87acd6a6a94f322f936bcc, source_bundle_figures_2_4/
  fig6A_contingency_cells_censor_aware.csv
  fig6B_compact_joined_1360.csv
  fig6C_compact_{kc,dkth,strength}_endurance.csv, fig6_manuscript_statistics_table.csv
"""
from __future__ import annotations

import csv
import json
import math
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style_common import FIGSIZE_SINGLE_COL, FIGSIZE_DOUBLE_COL, add_panel_label, savefig_all, sha256_of

PKG = Path(__file__).resolve().parents[1]
BUNDLE = Path("/Volumes/Data/Data/Nanopillar_calculation/PF-fracture-fatigue_worktrees/"
              "v10230-final-manuscript-figure-package/artifacts/paper_simulation_completion/"
              "source_bundle_figures_2_4")
SRC_OUT = PKG / "04_SOURCE_DATA" / "MAIN_TEXT"
PANELS_OUT = PKG / "01_MAIN_TEXT" / "INDIVIDUAL_PANELS"
COMPOSITE_OUT = PKG / "01_MAIN_TEXT" / "COMPOSITE_FIGURES"
PDF_OUT = PKG / "01_MAIN_TEXT" / "PDF"
SVG_OUT = PKG / "01_MAIN_TEXT" / "SVG"
PNG_OUT = PKG / "01_MAIN_TEXT" / "PNG_600DPI"

FAMILY_LABEL = {
    "strength_vs_fracture_class": "Strength vs.\nFracture class",
    "fracture_vs_growth_threshold_class": "Fracture vs.\nGrowth-threshold class",
    "strength_vs_growth_threshold_class": "Strength vs.\nGrowth-threshold class",
    "fracture_vs_fatigue_temperature_phenotype": "Fracture vs.\nS-N phenotype",
    "strength_vs_fatigue_temperature_phenotype": "Strength vs.\nS-N phenotype",
    "growth_threshold_vs_SN_temperature_phenotype": "Growth-threshold vs.\nS-N phenotype",
}
CONTEXT_LABEL = {
    "ctx_FCC_like_case29": "FCC-like", "ctx_shifted_ductile_case64": "Shifted ductile",
    "ctx_steep_cleavage_case35": "Steep cleavage", "ctx_slow_threshold_case101": "Slow threshold",
    "ctx_higher_barrier_case171": "Higher barrier", "ctx_plastic_shielded_case64_M1": "Plastic shielded",
}
FAMILY_ORDER = list(FAMILY_LABEL); CONTEXT_ORDER = list(CONTEXT_LABEL)


def _read_csv(name):
    with (BUNDLE / name).open() as fh:
        return list(csv.DictReader(fh))


def _cramers_v_matrix(cells):
    import pandas as pd
    df = pd.read_csv(BUNDLE / "fig6A_contingency_cells_censor_aware.csv")
    mat = np.full((len(FAMILY_ORDER), len(CONTEXT_ORDER)), np.nan)
    for i, fam in enumerate(FAMILY_ORDER):
        for j, ctx in enumerate(CONTEXT_ORDER):
            sub = df[(df.analysis_family == fam) & (df.context_id == ctx)]
            if sub.empty:
                continue
            tab = sub.pivot(index="row_class", columns="column_class", values="observed").fillna(0)
            if tab.shape[0] < 2 or tab.shape[1] < 2:
                continue
            chi2, p, _, _ = chi2_contingency(tab, correction=False)
            n = tab.values.sum(); k = min(tab.shape)
            mat[i, j] = math.sqrt(chi2 / max(n * (k - 1), 1.0))
    return mat


def panel_A(ax):
    mat = _cramers_v_matrix(None)
    im = ax.imshow(mat, cmap="magma_r", vmin=0, vmax=1.0, aspect="auto")
    ax.set_xticks(range(len(CONTEXT_ORDER))); ax.set_xticklabels([CONTEXT_LABEL[c] for c in CONTEXT_ORDER],
                                                                   rotation=45, ha="right", fontsize=6.5)
    ax.set_yticks(range(len(FAMILY_ORDER))); ax.set_yticklabels([FAMILY_LABEL[f] for f in FAMILY_ORDER], fontsize=6.5)
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            if not np.isnan(mat[i, j]):
                ax.text(j, i, f"{mat[i,j]:.2f}", ha="center", va="center", fontsize=6.5,
                        color="white" if mat[i, j] > 0.5 else "black")
    cb = plt.colorbar(im, ax=ax, pad=0.02)
    cb.set_label("Cramer's V (magnitude; nonnegative by construction)", fontsize=7)
    ax.set_title("Categorical association magnitude\n(direction stated in caption where relevant)", fontsize=8.5)


def panel_B(ax):
    rows = _read_csv("fig6B_compact_joined_1360.csv")
    cmap = plt.get_cmap("tab10")
    for i, ctx in enumerate(CONTEXT_ORDER):
        rs = [r for r in rows if r["fracture_context"] == ctx]
        kc = [float(r["Kc_first_MPa_sqrtm"]) for r in rs]
        dkth = [float(r["DeltaK_th_MPa_sqrtm"]) for r in rs]
        ax.scatter(kc, dkth, s=6, alpha=0.5, color=cmap(i), label=CONTEXT_LABEL[ctx])
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlabel(r"$K_c$ (MPa$\sqrt{\mathrm{m}}$)")
    ax.set_ylabel(r"$\Delta K_{th}$ (MPa$\sqrt{\mathrm{m}}$)")
    ax.set_title(f"n=1360 matched observations\npooled log-space Pearson $r\\approx$0.9865", fontsize=8.5)
    ax.legend(fontsize=5.5, loc="upper left", markerscale=2, ncol=1, bbox_to_anchor=(1.0, 1.0))


def panel_C(ax):
    manuscript = _read_csv("fig6_manuscript_statistics_table.csv")
    panelC = [r for r in manuscript if r["figure_panel"] == "C"]
    families = sorted(set(r["analysis_family"] for r in panelC))
    fam_marker = {"SN_endurance_vs_Kc_same_T": "o",
                  "SN_endurance_vs_DKth_same_T": "s",
                  "SN_endurance_vs_strength_metric::available_anomaly_gain_frac_exact": "^"}
    fam_display = {"SN_endurance_vs_Kc_same_T": r"$K_c$",
                   "SN_endurance_vs_DKth_same_T": r"$\Delta K_{th}$",
                   "SN_endurance_vs_strength_metric::available_anomaly_gain_frac_exact": "Strength anomaly"}
    for fam in families:
        rs = [r for r in panelC if r["analysis_family"] == fam and r["estimate"]]
        T = [float(r["temperature_K"]) for r in rs]
        auc = [float(r["estimate"]) for r in rs]
        lo = [float(r["estimate"]) - float(r["ci95_low"]) if r["ci95_low"] else 0 for r in rs]
        hi = [float(r["ci95_high"]) - float(r["estimate"]) if r["ci95_high"] else 0 for r in rs]
        # jitter by family for visibility
        jitter = {"SN_endurance_vs_Kc_same_T": -8, "SN_endurance_vs_DKth_same_T": 0,
                  "SN_endurance_vs_strength_metric::available_anomaly_gain_frac_exact": 8}[fam]
        Tj = [t + jitter for t in T]
        ax.errorbar(Tj, auc, yerr=[lo, hi], fmt=fam_marker[fam], markersize=5, capsize=2,
                    label=fam_display[fam], linewidth=1.0)
    ax.axhline(0.5, color="0.4", linestyle="--", linewidth=1.0, label="Chance (AUC=0.5)")
    ax.set_xlabel("Temperature (K)")
    ax.set_ylabel("AUC (endurance-like vs.\ncontinuous S-N)")
    ax.set_ylim(0, 1.05)
    ax.set_title("Temperature-specific AUC, all 6 contexts\n(strict S-N definition, 95% bootstrap CI)", fontsize=8.5)
    ax.legend(fontsize=6, loc="lower right")


def composite():
    fig, axes = plt.subplots(1, 3, figsize=(FIGSIZE_DOUBLE_COL[0] * 1.15, FIGSIZE_DOUBLE_COL[1] * 0.85))
    panel_A(axes[0]); add_panel_label(axes[0], "A")
    panel_B(axes[1]); add_panel_label(axes[1], "B")
    panel_C(axes[2]); add_panel_label(axes[2], "C")
    fig.suptitle("Figure 6. Cross-phenomenon relationships generated by the shared barrier landscape",
                 fontsize=9, y=1.04)
    fig.tight_layout()
    return fig


def main():
    SRC_OUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for name in ["fig6A_contingency_cells_censor_aware.csv", "fig6B_compact_joined_1360.csv",
                 "fig6C_compact_kc_endurance.csv", "fig6C_compact_dkth_endurance.csv",
                 "fig6C_compact_strength_endurance.csv", "fig6_manuscript_statistics_table.csv"]:
        dest = SRC_OUT / name
        dest.write_bytes((BUNDLE / name).read_bytes())
        manifest[name] = sha256_of(dest)

    hashes = {}
    for letter, fn in zip("ABC", [panel_A, panel_B, panel_C]):
        fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE_COL)
        fn(ax); add_panel_label(ax, letter)
        fig.tight_layout()
        stem = f"Fig6{letter}"
        hashes[stem] = savefig_all(fig, stem, PANELS_OUT, PANELS_OUT, PANELS_OUT)
        savefig_all(fig, stem, PDF_OUT, SVG_OUT, PNG_OUT)
        plt.close(fig)

    fig_comp = composite()
    hashes["Figure6_composite"] = savefig_all(fig_comp, "Figure6_composite", COMPOSITE_OUT, COMPOSITE_OUT, COMPOSITE_OUT)
    savefig_all(fig_comp, "Figure6_composite", PDF_OUT, SVG_OUT, PNG_OUT)
    plt.close(fig_comp)

    (SRC_OUT / "fig6_source_data_hashes.json").write_text(json.dumps(
        dict(source_files=manifest, figure_hashes=hashes), indent=2, default=str))
    print("Figure 6: wrote 3 panels + 1 composite")


if __name__ == "__main__":
    main()
