#!/usr/bin/env python3
"""Prepare the four-candidate deterministic shielding-history scout.

Candidate material manifests are generated by the validated v10.1.7.5 transfer
utility, including the fixed v9.10.4 shielding-cap provenance.  The case table
is then restricted to the four mechanism states needed to identify a
shielding-history-coupled DBTT response.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import pandas as pd

from scripts.prepare_v10_1_7_5_candidate_transfer import prepare as prepare_transfer


DEFAULT_CANDIDATES = (
    "DBTT_A0002333",
    "DBTT_A0002277",
    "DBTT_A0005137",
    "DBTT_A0003837",
)
SCOUT_MODES = (
    "full",
    "plasticity_off",
    "shielding_off",
    "backstress_off",
)


def prepare_shielding_scout(
    source: pd.DataFrame,
    candidate_ids: list[str],
    out: Path,
) -> pd.DataFrame:
    all_cases = prepare_transfer(source, candidate_ids, out)
    cases = all_cases[all_cases["mode"].astype(str).isin(SCOUT_MODES)].copy()
    cases["mode"] = pd.Categorical(cases["mode"], SCOUT_MODES, ordered=True)
    cases = cases.sort_values(
        ["candidate_id", "T_K", "mode"], kind="stable"
    ).reset_index(drop=True)
    cases["mode"] = cases["mode"].astype(str)

    expected = len(candidate_ids) * 2 * len(SCOUT_MODES)
    if len(cases) != expected:
        raise ValueError(f"expected {expected} scout cases; built {len(cases)}")
    if cases.groupby("candidate_id")["T_K"].nunique().ne(2).any():
        raise ValueError("every candidate must have exactly two endpoint temperatures")

    cases.to_csv(out / "shielding_scout_cases.csv", index=False)
    cases.to_csv(out / "shielding_scout_cases.tsv", index=False, sep="\t")
    return cases


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--candidates", nargs="+", default=list(DEFAULT_CANDIDATES))
    args = parser.parse_args()

    source_path = args.source.resolve()
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)
    candidates = list(args.candidates)
    cases = prepare_shielding_scout(pd.read_csv(source_path), candidates, out)

    provenance = {
        "schema": "v10.1.7.6_four_candidate_shielding_scout_preparation",
        "source": str(source_path),
        "source_sha256": hashlib.sha256(source_path.read_bytes()).hexdigest(),
        "candidate_ids": candidates,
        "modes": list(SCOUT_MODES),
        "n_candidates": len(candidates),
        "n_endpoints_per_candidate": 2,
        "n_cases": int(len(cases)),
        "fixed_campaign_fields": str(out / "fixed_field_provenance.json"),
    }
    (out / "shielding_scout_preparation.json").write_text(
        json.dumps(provenance, indent=2)
    )

    summary = cases.groupby(
        ["candidate_id", "transition_bracket"], as_index=False
    ).agg(
        endpoint_temperatures=(
            "T_K",
            lambda values: json.dumps(sorted(set(float(v) for v in values))),
        ),
        n_cases=("mode", "count"),
    )
    print(summary.to_string(index=False), flush=True)
    print(f"wrote {len(cases)} scout cases to {out / 'shielding_scout_cases.tsv'}")


if __name__ == "__main__":
    main()
